services:
  db:
    image: "postgres:16-alpine"
    container_name: db
    environment:
      - POSTGRES_DB=cohort
      - POSTGRES_USER=cohort
      - POSTGRES_PASSWORD=cohort
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  api:
    image: my-backend
    container_name: api
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_PROFILES_ACTIVE: docker
volumes:
  pgdata:
